add_newline = true

[character]
success_symbol = "[❯](bold green)" #
error_symbol = "[❯](bold red)" 

[username]
disabled = false
show_always = true
style_user = "bold #ff6600"
style_root = "bold blue"
format = "[$user]($style) in "

[directory]
truncation_length = 50
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold #cccc00"

[git_branch]
symbol = ""
style = "bold #00cc00"

[git_status]
conflicted = "${count}="
ahead = "${count}↑"
behind = "${count}↓"
diverged = "${count}⇕"
untracked = "${count}?"
stashed = "${count}*"
modified = "${count}!"
staged = '[++\($count\)](green)'
renamed = "${count}»"
deleted = "${count}✘"
style = "bold #0099ff"

[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[aws]
disabled = true
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "🅰 "

[aws.region_aliases]
ap-northeast = "jp"
ap-southeast-2 = "au"
us-east-1 = "va"

[package]
disabled = false